name: Setup

runs:
  using: composite
  steps:
    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: yarn
    - name: Cache
      uses: actions/cache@v2
      id: cache
      with:
        path: '**/node_modules'
        key: yarn-v1-${{ hashFiles('**/yarn.lock') }}
    - name: Install
      if: steps.cache.outputs.cache-hit != 'true'
      run: yarn --prefer-offline
      shell: bash