name: Deploy

on:
  push:
    branches:
      - tasks/support_custom_tokens_source_setters

jobs:
  deploy-avalanche-test:
      name: Deploy Avalanche
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Set up environment
          uses: ./.github/actions/setup
        - name: Deploy Avalanche
          env:
            GRAPH_KEY: ${{ secrets.GRAPH_STUDIO_KEY }}
            VERSION_LABEL: ${{ github.sha }}
          run: yarn deploy:avalanche
