name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy-arbitrum:
    name: Deploy Arbitrum
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Deploy Arbitrum
        env:
          GRAPH_KEY: ${{ secrets.GRAPH_STUDIO_KEY }}
          VERSION_LABEL: ${{ github.sha }}
        run: yarn deploy:arbitrum

  deploy-aurora:
    name: Deploy Aurora
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Deploy Aurora
        env:
          GRAPH_KEY: ${{ secrets.GRAPH_STUDIO_KEY }}
          VERSION_LABEL: ${{ github.sha }}
        run: yarn deploy:aurora

  deploy-avalanche:
      name: Deploy Avalanche
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Set up environment
          uses: ./.github/actions/setup
        - name: Deploy Avalanche
          env:
            GRAPH_KEY: ${{ secrets.GRAPH_STUDIO_KEY }}
            VERSION_LABEL: ${{ github.sha }}
          run: yarn deploy:avalanche

  deploy-base:
      name: Deploy Base
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Set up environment
          uses: ./.github/actions/setup
        - name: Deploy Base
          env:
            VERSION_LABEL: ${{ github.sha }}
            GRAPH_KEY: ${{ secrets.GRAPH_STUDIO_KEY }}
          run: yarn deploy:base

  deploy-bsc:
      name: Deploy BSC
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Set up environment
          uses: ./.github/actions/setup
        - name: Deploy BSC
          env:
            GRAPH_KEY: ${{ secrets.GRAPH_STUDIO_KEY }}
            VERSION_LABEL: ${{ github.sha }}
          run: yarn deploy:bsc

  deploy-fantom:
      name: Deploy Fantom
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Set up environment
          uses: ./.github/actions/setup
        - name: Deploy Fantom
          env:
            GRAPH_KEY: ${{ secrets.GRAPH_STUDIO_KEY }}
            VERSION_LABEL: ${{ github.sha }}
          run: yarn deploy:fantom

  deploy-gnosis:
      name: Deploy Gnosis
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Set up environment
          uses: ./.github/actions/setup
        - name: Deploy Gnosis
          env:
            GRAPH_KEY: ${{ secrets.GRAPH_STUDIO_KEY }}
            VERSION_LABEL: ${{ github.sha }}
          run: yarn deploy:gnosis

  deploy-mainnet:
      name: Deploy Mainnet
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Set up environment
          uses: ./.github/actions/setup
        - name: Deploy Mainnet
          env:
            GRAPH_KEY: ${{ secrets.GRAPH_STUDIO_KEY }}
            VERSION_LABEL: ${{ github.sha }}
          run: yarn deploy:mainnet

  deploy-optimism:
      name: Deploy Optimism
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Set up environment
          uses: ./.github/actions/setup
        - name: Deploy Optimism
          env:
            GRAPH_KEY: ${{ secrets.GRAPH_STUDIO_KEY }}
            VERSION_LABEL: ${{ github.sha }}
          run: yarn deploy:optimism

  deploy-polygon:
      name: Deploy Polygon
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Set up environment
          uses: ./.github/actions/setup
        - name: Deploy Polygon
          env:
            GRAPH_KEY: ${{ secrets.GRAPH_STUDIO_KEY }}
            VERSION_LABEL: ${{ github.sha }}
          run: yarn deploy:polygon

  deploy-zkevm:
      name: Deploy zkEVM
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Set up environment
          uses: ./.github/actions/setup
        - name: Deploy zkEVM
          env:
            GRAPH_KEY: ${{ secrets.GRAPH_STUDIO_KEY }}
            VERSION_LABEL: ${{ github.sha }}
          run: yarn deploy:zkevm
